import type { Asset } from "@/core/types";

export const assets: Asset[] = [
  {
    type: "patriot_battery",
    classification: "long_range_sam",
    cost_system: 6000000,
    cost_per_shot: 1000000,
    range_km: 160,
    engagement_ceiling: [100, 30000],
    kill_probability: 0.85,
    reload_seconds: 3600,
    ammo_capacity: 16,
    rate_of_fire_rpm: 1,
    targeting_speed: "fast",
    vulnerabilities: ["swarm_saturation", "cost_asymmetry"],
    detection_capabilities: ["radar"],
  },
  {
    type: "nasams",
    classification: "medium_range_sam",
    cost_system: 2000000,
    cost_per_shot: 400000,
    range_km: 40,
    engagement_ceiling: [30, 20000],
    kill_probability: 0.8,
    reload_seconds: 1800,
    ammo_capacity: 12,
    rate_of_fire_rpm: 2,
    targeting_speed: "fast",
    vulnerabilities: ["swarm_saturation"],
    detection_capabilities: ["radar"],
  },
  {
    type: "gepard",
    classification: "spaag_ciws",
    cost_system: 500000,
    cost_per_shot: 50,
    range_km: 4,
    engagement_ceiling: [0, 3000],
    kill_probability: 0.65,
    reload_seconds: 120,
    ammo_capacity: 640,
    rate_of_fire_rpm: 550,
    targeting_speed: "fast",
    vulnerabilities: ["high_altitude_blind"],
    detection_capabilities: ["radar", "visual"],
  },
  {
    type: "laser_cuas",
    classification: "directed_energy",
    cost_system: 1000000,
    cost_per_shot: 10,
    range_km: 2,
    engagement_ceiling: [0, 2000],
    kill_probability: 0.7,
    reload_seconds: 5,
    ammo_capacity: 9999,
    rate_of_fire_rpm: 12,
    targeting_speed: "medium",
    vulnerabilities: ["weather_dependent", "short_range"],
    detection_capabilities: ["visual", "thermal"],
  },
  {
    type: "cellular_detector",
    classification: "passive_sensor",
    cost_system: 50000,
    cost_per_shot: 0,
    range_km: 15,
    engagement_ceiling: [0, 5000],
    kill_probability: 0,
    reload_seconds: 0,
    ammo_capacity: 0,
    rate_of_fire_rpm: 0,
    targeting_speed: "fast",
    vulnerabilities: [],
    detection_capabilities: ["cellular_imei"],
  },
  {
    type: "thermal_sensor",
    classification: "passive_sensor",
    cost_system: 80000,
    cost_per_shot: 0,
    range_km: 10,
    engagement_ceiling: [0, 6000],
    kill_probability: 0,
    reload_seconds: 0,
    ammo_capacity: 0,
    rate_of_fire_rpm: 0,
    targeting_speed: "medium",
    vulnerabilities: ["weather_dependent"],
    detection_capabilities: ["thermal"],
  },
];
