import type { Threat } from "@/core/types";

export const threats: Threat[] = [
  {
    type: "geran_2",
    classification: "loitering_munition",
    domain: "air",
    speed_ms: 50,
    altitude_m: [50, 4000],
    range_km: 2500,
    cost_usd: 20000,
    warhead_kg: 50,
    signature: { rcs: 0.3, thermal: "medium", acoustic_db: 90, visual: "medium" },
    navigation: ["INS", "GLONASS", "starlink"],
    jamming_resistance: { traditional_ew: 0.7, russian_tobol: 0.3 },
    special_traits: ["starlink_capable", "mass_producible"],
    behavior_tree: "cruise_strike",
  },
  {
    type: "geran_5",
    classification: "cruise_missile_analog",
    domain: "air",
    speed_ms: 167,
    altitude_m: [0, 6000],
    range_km: 950,
    cost_usd: 200000,
    warhead_kg: 90,
    signature: { rcs: 0.5, thermal: "medium", acoustic_db: 85, visual: "low" },
    navigation: ["INS", "CRP_antenna", "starlink"],
    jamming_resistance: { traditional_ew: 0.95, russian_tobol: 0.5 },
    special_traits: ["high_altitude_inaccessible", "speed_asymmetry"],
    behavior_tree: "high_altitude_penetration",
  },
  {
    type: "shahed_238",
    classification: "jet_loitering_munition",
    domain: "air",
    speed_ms: 55,
    altitude_m: [100, 5000],
    range_km: 1500,
    cost_usd: 50000,
    warhead_kg: 40,
    signature: { rcs: 0.25, thermal: "medium", acoustic_db: 80, visual: "low" },
    navigation: ["INS", "thermal_imaging", "GPS"],
    jamming_resistance: { traditional_ew: 0.85, russian_tobol: 0.4 },
    special_traits: ["gps_denied_capable", "thermal_backup"],
    behavior_tree: "terrain_following",
  },
  {
    type: "fpv_kamikaze",
    classification: "fpv_drone",
    domain: "air",
    speed_ms: 11,
    altitude_m: [1, 300],
    range_km: 15,
    cost_usd: 500,
    warhead_kg: 1.5,
    signature: { rcs: 0.01, thermal: "low", acoustic_db: 65, visual: "low" },
    navigation: ["LTE_4G", "visual_fpv"],
    jamming_resistance: { traditional_ew: 0.3, russian_tobol: 0.1 },
    special_traits: ["IMEI_detectable", "terrain_masking", "mass_producible"],
    behavior_tree: "nap_of_earth",
  },
  {
    type: "geran_2_manpads",
    classification: "air_to_air_loitering",
    domain: "air",
    speed_ms: 50,
    altitude_m: [500, 4000],
    range_km: 6.5,
    cost_usd: 30000,
    warhead_kg: 3,
    signature: { rcs: 0.3, thermal: "medium", acoustic_db: 88, visual: "medium" },
    navigation: ["INS", "GLONASS"],
    jamming_resistance: { traditional_ew: 0.6, russian_tobol: 0.25 },
    special_traits: ["rear_aspect_attack", "trails_swarm"],
    behavior_tree: "escort_intercept",
  },
  {
    type: "molniya_minelayer",
    classification: "minelaying_drone",
    domain: "air",
    speed_ms: 30,
    altitude_m: [10, 500],
    range_km: 100,
    cost_usd: 15000,
    warhead_kg: 20,
    signature: { rcs: 0.15, thermal: "low", acoustic_db: 70, visual: "low" },
    navigation: ["INS", "GPS"],
    jamming_resistance: { traditional_ew: 0.5, russian_tobol: 0.2 },
    special_traits: ["pfm1_mine_drop", "evacuation_route_denial"],
    behavior_tree: "area_denial",
  },
  {
    type: "strike_ugv",
    classification: "ground_combat_vehicle",
    domain: "ground",
    speed_ms: 8,
    altitude_m: [0, 0],
    range_km: 50,
    cost_usd: 8000,
    warhead_kg: 10,
    signature: { rcs: 1.5, thermal: "high", acoustic_db: 95, visual: "high" },
    navigation: ["INS", "visual_AI"],
    jamming_resistance: { traditional_ew: 0.8, russian_tobol: 0.6 },
    special_traits: ["cope_cage_armor", "surrender_mechanic"],
    behavior_tree: "ground_assault",
  },
  {
    type: "usv_magura",
    classification: "unmanned_surface_vessel",
    domain: "maritime",
    speed_ms: 20,
    altitude_m: [0, 0],
    range_km: 800,
    cost_usd: 250000,
    warhead_kg: 200,
    signature: { rcs: 2.0, thermal: "medium", acoustic_db: 100, visual: "medium" },
    navigation: ["INS", "starlink", "visual"],
    jamming_resistance: { traditional_ew: 0.9, russian_tobol: 0.7 },
    special_traits: ["aim9x_capable", "sea_defense"],
    behavior_tree: "maritime_strike",
  },
  {
    type: "equine_relay_node",
    classification: "mobile_comms_relay",
    domain: "ground",
    speed_ms: 2.2,
    altitude_m: [0, 0],
    range_km: 30,
    cost_usd: 5000,
    warhead_kg: 0,
    signature: { rcs: 0.8, thermal: "high_confusion", acoustic_db: 40, visual: "medium" },
    navigation: ["INS", "starlink"],
    jamming_resistance: { traditional_ew: 0.95, russian_tobol: 0.8 },
    special_traits: ["starlink_terminal", "cellular_only_detection", "biological_thermal"],
    behavior_tree: "patrol_relay",
  },
];
